### ISSUE TITLE
LIBPATHS and EXTRA_LIBS  appending not work for app's Makefile

### ISSUE THREAD

**Issue by dangbinghoo** [apache/nuttx-apps#1058]
if  put bellow in user apps Makefile 

``` Makefile
EXTRA_LIBPATHS += -L $(PWD)
LIBPATHS += $(PWD)
EXTRA_LIBS += -lnimcache
```
it seems, when linking the final binary,  these flags were not appended to  LD.

and CFLAGS += also won't work, IS there any way to achieve this ?

**Comment by xiaoxiang781216** [comment]
Yes, nuttx/Makefile invoke but not include apps/Makefile. So the change to EXTRA_LIBPATHS/EXTRA_LIBS can't propagate to nuttx/Makefile.

**Comment by xiaoxiang781216** [comment]
It is welcome to provide a solution fix this problem.

**Comment by dangbinghoo** [comment]
> 

is there any nuttx talking groups or what exists? 
PS: I'm from CN, QQ group is ok.

**Comment by xiaoxiang781216** [comment]
Yes, here: https://nuttx.apache.org/community/

**Comment by xiaoxiang781216** [comment]
@dangbinghoo Fixed by https://github.com/apache/nuttx/pull/11202
