### ISSUE TITLE
LVGL v8 version upgrade

### ISSUE THREAD

**Issue by FASTSHIFT** [apache/nuttx-apps#1322]
[LVGL v8](https://github.com/lvgl/lvgl/releases/tag/v8.3.1)  has been released for a while, and we should consider upgrading `graphics/lvgl` to that version.

Modifications that may be involved in an upgrade:
1. Delete LVGL v7-based Makefile, Kconfig configuration file, and related dependency files.
2. Add new and better porting based on LVGL v8, including fb, lcd, button, etc.
3. Modify `examples/lvgldemo`, use the demo of LVGL v8, and remove the porting function here.

Is there anything else?

**Comment by acassis** [comment]
@FASTSHIFT yes, please helps us if you can, adding v8 support will allow us to use SquareLine Studio to create interfaces very easily!

**Comment by xiaoxiang781216** [comment]
@lupyuen we plan to upgrade lvgl from v7 to v8, do you have any concern?

**Comment by lupyuen** [comment]
Tested OK on PinePhone. Thanks everyone! :-)

![PXL_20230101_135322546~2.jpg](https://user-images.githubusercontent.com/9960133/210173953-c3d7a440-82c9-4565-bfa8-e8c36c0411fe.jpg)
