### ISSUE TITLE
Unable to build cJSON

### ISSUE THREAD

**Issue by SPRESENSE** [apache/nuttx-apps#1516]
I get a build error with cJSON when building `examples/json`.
```
Downloading: v1.7.12.tar.gz
curl -O -L "https://github.com/DaveGamble/cJSON/archive"/v1.7.12.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  340k    0  340k    0     0   747k      0 --:--:-- --:--:-- --:--:-- 2707k
Unpacking: v1.7.12.tar.gz -> cJSON
tar -zxf v1.7.12.tar.gz
touch cJSON
cp cJSON/cJSON.h /xxx/include/netutils/cJSON.h
cp: cannot stat 'cJSON/cJSON.h': Not a directory
```
This error is caused by this commit https://github.com/apache/nuttx-apps/pull/1512/commits/ad319360eb704efe1933e73cae8046c296d03180. (https://github.com/apache/nuttx-apps/pull/1512)
I don't know the purpose of this commit. Please correct it.

**Comment by xiaoxiang781216** [comment]
> This error is caused by this commit [ad31936](https://github.com/apache/nuttx-apps/commit/ad319360eb704efe1933e73cae8046c296d03180). (#1512) I don't know the purpose of this commit.

The idea is simple: if user already have git locally, it's better to skip the donwload process. This patch make the intention from https://github.com/apache/nuttx-apps/pull/1295 work for cJSON.

> Please correct it.

@pengxiang-hao please fix it, look like the mainline doesn't enable cJSON for daily ci:(.
