### ISSUE TITLE
Requesting justification for bad code pattern

### ISSUE THREAD

**Issue by slorquet** [apache/nuttx-apps#1643]
Hello,
What is the exact reason for this wasteful array that could be replaced by a sprintf?

https://github.com/apache/nuttx/blob/master/libs/libc/string/lib_strsignal.c#L37

Thank you.

**Comment by pkarashchenko** [comment]
I think with `sprintf` you can't make `strsignal` reentrant.

**Comment by slorquet** [comment]
Is there really no other way to implement this? It looks particularly inefficient.

**Comment by pkarashchenko** [comment]
Not that I'm aware of. You can see that other cases in switch/case also have a common `SIG` part of the string. The only difference is that in the array it is a bit longer.
Let me think a bit of what can be an option. Maybe having a reentrant variant can be a config option or we can return just the number string and drop `Signal ` prefix

**Comment by pkarashchenko** [comment]
@slorquet can we close this issue now?

**Comment by slorquet** [comment]
we can :)
