### ISSUE TITLE
Changes to NuttX relating to c++ reserved words has broken apps

### ISSUE THREAD

**Issue by TimJTi** [apache/nuttx-apps#2078]
Nuttx [PR10565](https://github.com/apache/nuttx/pull/10565) has renamed things to avoid the use of c++ reserved names such as public.

The Apps repo escaped the attentions of that work and now won't build.
For example:

- nsh_syscmds.c line 768 `nsh_write(vtbl, stream.buffer, stream.public.nput);`
- hex2bin_main.c line 230 `  ret = hex2bin(&stdinstream.public, &stdoutstream.public`
- dhex2mem_main.c line 213 `ret = hex2bin(&stdinstream.public, &memoutstream.public`

**Comment by danielappiagyei-bc** [comment]
@TimJTi 
I think your nuttx-apps repo is out of sync with the nuttx repo, can you merge master? There was a complementary PR [here](https://github.com/apache/nuttx-apps/pull/2047) that merged right after the nuttx one.

Master already has these changes, e.g.,
- https://github.com/apache/nuttx-apps/blob/master/nshlib/nsh_syscmds.c#L769

**Comment by TimJTi** [comment]
> @TimJTi I think your nuttx-apps repo is out of sync with the nuttx repo, can you merge master? There was a complementary PR [here](https://github.com/apache/nuttx-apps/pull/2047) that merged right after the nuttx one.
> 
> Master already has these changes, e.g.,
> 
>     * https://github.com/apache/nuttx-apps/blob/master/nshlib/nsh_syscmds.c#L769

I thought I had...I'll double check!
