### ISSUE TITLE
Compilation failure due to improper handling of CAN utils lely-core package

### ISSUE THREAD

**Issue by PwnVerse** [apache/nuttx-apps#2181]
Compilation fails when a board configuration (tested out with config `raspberrypi-pico-w:nsh`) with CAN support enabled from Application configuration of the menuconfig with the following logs- 

```sh
make -j20
Create version.h
LN: platform/board to /home/ritvik/Desktop/Files/Fuzzing_RTOS_Applications/Ported_Applications/nuttxspace/apps/platform/dummy
Unpacking: lely-core-a2ecf70b76a42c25c5338d86e85250bf16fd7023.tar.gz -> lely-core-master-a2ecf70b76a42c25c5338d86e85250bf16fd7023
mv: cannot stat 'lely-core-master-a2ecf70b76a42c25c5338d86e85250bf16fd7023': No such file or directory
```

On inspection in the directory where the lely package is unpacked, it is observed that the package hash is different from the tar hash.

![image](https://github.com/apache/nuttx-apps/assets/43813479/8f02db94-3e48-43a9-81f8-857c716745cc)

The Makefile in `apps/canutils/lely-canopen` assumes that the hash is the same and errors out since there's no matching directory

```sh
LELYCANOPEN_TARBALL = lely-core-$(LELYCANOPEN_VERSION).tar.gz
LELYCANOPEN_UNPACKNAME = lely-core-master-$(LELYCANOPEN_VERSION)
```

**Comment by xiaoxiang781216** [comment]
could you provide patch to fix this?
