### ISSUE TITLE
rpporxy does not work

### ISSUE THREAD

**Issue by Jan9401** [apache/nuttx-apps#2277]
./tool/configure.sh -l sim:rpproxy

system will be hang.

**Comment by xiaoxiang781216** [comment]
could you show more log?

**Comment by Jan9401** [comment]
The terminal does not have any logs. It is relatively easy to reproduce this problem.

./tool/configure.sh -l sim:rppoxy
make -j16
./nuttx

**Comment by xiaoxiang781216** [comment]
you need run sim:rpserver too, please read:
https://github.com/apache/nuttx/blob/master/Documentation/platforms/sim/sim/boards/sim/index.rst#rpproxy-and-rpserver

**Comment by Jan9401** [comment]
I run sim:rpserver too, But it will hang too. 
![Screenshot from 2024-01-31 22-03-51](https://github.com/apache/nuttx-apps/assets/68552941/25f1c86a-c0a7-49e2-a98f-5b859f8c4bd9)
![Screenshot from 2024-01-31 22-04-15](https://github.com/apache/nuttx-apps/assets/68552941/d02f4074-1f47-4630-8d8f-d2a9c55a9bf3)

**Comment by xiaoxiang781216** [comment]
@CV-Bowen could you look at this problem?

**Comment by CV-Bowen** [comment]
> @CV-Bowen could you look at this problem?

Yes, i will take look today.

**Comment by CV-Bowen** [comment]
@Jan9401 Hi, we make /dev/ttyproxy be /dev/console in rpproxy by using uart rpmsg, so the terminal runs ./rpproxy hang at startup is normal.
You can use `cu` command to enter the rpproxy nsh, like this:
![image](https://github.com/apache/nuttx-apps/assets/39286361/38ad72f8-fccf-4c44-827d-2ff4935d4e63)

**Comment by Jan9401** [comment]
> @Jan9401 Hi, we make /dev/ttyproxy be /dev/console in rpproxy by using uart rpmsg, so the terminal runs ./rpproxy hang at startup is normal. You can use `cu` command to enter the rpproxy nsh, like this: ![image](https://private-user-images.githubusercontent.com/39286361/301473985-38ad72f8-fccf-4c44-827d-2ff4935d4e63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODUzOTIsIm5iZiI6MTcwNjc4NTA5MiwicGF0aCI6Ii8zOTI4NjM2MS8zMDE0NzM5ODUtMzhhZDcyZjgtZmNjZi00YzQ0LTgyN2QtMmZmNDkzNWQ0ZTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEwNTgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYTc4YjI5MDJiYjI5OWQwOTZjMDc0MzY3NTM1YTQyZmE2ZDE0ZjQ0Yzc5NTY1MDY2NmY1YWNmMWU1NGRjYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JqYNn_kBOs8aIsKfEL-AnH4cLLkhu38BJQL830Rt15U)

OK Thanks.
