### ISSUE TITLE
[BUG] `ramtest` application CMakeList error.

### ISSUE THREAD

**Issue by nonpawite** [apache/nuttx-apps#2551]
### Description / Steps to reproduce the issue

`ramtest` application's CMakeList are reading for `CONFIG_SYSTEM_RAMTEST` in if clause, but in configuration file are defined as `CONFIG_TESTING_RAMTEST`. Which result in `ramtest` application is not showing in nsh shell when user enabled the applocation in menuconfig.

When `CONFIG_SYSTEM_RAMTEST` changed to `CONFIG_TESTING_RAMTEST` the application shows in nsh shell normally.

### On which OS does this issue occur?

[Linux]

### What is the version of your OS?

Ubuntu 24.04

### NuttX Version

master

### Issue Architecture

[all]

### Issue Area

[Applications]

### Verification

- [X] I have verified before submitting the report.

**Comment by acassis** [comment]
@nonpawite I think you are using an outdated apps repository, the CONFIG_SYSTEM_RAMTEST moved to CONFIG_TESTING_RAMTEST
